#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/peregrine?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      stat-view-servlet:
        enabled: true
        #        login-username: druid
        #        login-password: 123456
        reset-enable: true
        url-pattern: "/druid/*"
        # allow: 127.0.0.1
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        profile-enable: true
      aop-patterns: com.shuijing.peregrine.controller.*,com.shuijing.peregrine.service.*,com.shuijing.peregrine.mapper.*
      filter:
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true
  devtools:
    restart:
      enabled: true
      #        trigger-file: .reloadtrigger
      log-condition-evaluation-delta: false
      poll-interval: 20000
      quiet-period: 10000
  profiles:
    active: local
  mail:
    host: smtp.163.com
    username: xxx@163.com
    password: xxx
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  messages:
    basename: messages
    encoding: UTF-8
  quartz:
    #数据库方式
    job-store-type: JDBC
    #初始化表结构
    jdbc:
      initialize-schema: always
#      schema: classpath:tables_mysql_innodb.sql
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: peregrine

# 多邮件源
mail:
  from: xxx@163.com
  to: xxx@163.com
  configs:
    # 账号 1
    - username: xxx@163.com
      password: xxx
      host: smtp.163.com
      port: 25
      protocol: smtp
      default-encoding: UTF-8
    # 账号 2
    - username: xxx@QQ.com
      password: xxx
      host: smtp.QQ.com
      port: 25
      protocol: smtp
      default-encoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /peregrine
    session:
      timeout: 60

logging:
  level:
    root: debug
    # 输出 SQL
    druid.sql.Statement: debug
    # 输出查询结果
    druid.sql.ResultSet: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
